// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: Chitt_chat/Chitt_chat.proto

package Chitt_chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChittChat_Chat_FullMethodName = "/Chitt_chat.Chitt_chat/Chat"
)

// ChittChatClient is the client API for ChittChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittChatClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type chittChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChittChatClient(cc grpc.ClientConnInterface) ChittChatClient {
	return &chittChatClient{cc}
}

func (c *chittChatClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChittChat_ServiceDesc.Streams[0], ChittChat_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChittChat_ChatClient = grpc.BidiStreamingClient[Message, Message]

// ChittChatServer is the server API for ChittChat service.
// All implementations must embed UnimplementedChittChatServer
// for forward compatibility.
type ChittChatServer interface {
	Chat(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedChittChatServer()
}

// UnimplementedChittChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChittChatServer struct{}

func (UnimplementedChittChatServer) Chat(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChittChatServer) mustEmbedUnimplementedChittChatServer() {}
func (UnimplementedChittChatServer) testEmbeddedByValue()                   {}

// UnsafeChittChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittChatServer will
// result in compilation errors.
type UnsafeChittChatServer interface {
	mustEmbedUnimplementedChittChatServer()
}

func RegisterChittChatServer(s grpc.ServiceRegistrar, srv ChittChatServer) {
	// If the following call pancis, it indicates UnimplementedChittChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChittChat_ServiceDesc, srv)
}

func _ChittChat_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittChatServer).Chat(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChittChat_ChatServer = grpc.BidiStreamingServer[Message, Message]

// ChittChat_ServiceDesc is the grpc.ServiceDesc for ChittChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChittChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chitt_chat.Chitt_chat",
	HandlerType: (*ChittChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ChittChat_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Chitt_chat/Chitt_chat.proto",
}
