// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/dme.proto

package dme

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DME_RecieveToken_FullMethodName = "/dme.DME/RecieveToken"
)

// DMEClient is the client API for DME service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DMEClient interface {
	RecieveToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dMEClient struct {
	cc grpc.ClientConnInterface
}

func NewDMEClient(cc grpc.ClientConnInterface) DMEClient {
	return &dMEClient{cc}
}

func (c *dMEClient) RecieveToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DME_RecieveToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMEServer is the server API for DME service.
// All implementations must embed UnimplementedDMEServer
// for forward compatibility.
type DMEServer interface {
	RecieveToken(context.Context, *Token) (*emptypb.Empty, error)
	mustEmbedUnimplementedDMEServer()
}

// UnimplementedDMEServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDMEServer struct{}

func (UnimplementedDMEServer) RecieveToken(context.Context, *Token) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveToken not implemented")
}
func (UnimplementedDMEServer) mustEmbedUnimplementedDMEServer() {}
func (UnimplementedDMEServer) testEmbeddedByValue()             {}

// UnsafeDMEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DMEServer will
// result in compilation errors.
type UnsafeDMEServer interface {
	mustEmbedUnimplementedDMEServer()
}

func RegisterDMEServer(s grpc.ServiceRegistrar, srv DMEServer) {
	// If the following call pancis, it indicates UnimplementedDMEServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DME_ServiceDesc, srv)
}

func _DME_RecieveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMEServer).RecieveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DME_RecieveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMEServer).RecieveToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// DME_ServiceDesc is the grpc.ServiceDesc for DME service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DME_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dme.DME",
	HandlerType: (*DMEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecieveToken",
			Handler:    _DME_RecieveToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dme.proto",
}
